### ISSUE TITLE
Is Gensane & Ryckelynck's 11-square packing identical to the 1979 packing of Walter Trump?

### ISSUE THREAD

**Issue by hohMiyazawa** [erich-friedman/erich-friedman.github.io#3]
[Squares in squares](https://en.wikipedia.org/wiki/Square_packing_in_a_square) on Wikipedia has this to say:

> By contrast, the tightest known packing of 11 squares is inside a square of side length approximately 3.877084, slightly improving a similar packing found earlier by Walter Trump [[6]]

The reference pointing to Gensane, T., & Ryckelynck, P. (2004). Improved Dense Packings of Congruent Squares in a Square. Discrete & Computational Geometry, 34(1), 97–109.

> Case n = 11. The best known packing is due to Trump and apparently to many other
people. In [3] we find that s11 ≤ 3.8772 for a packing given in Fig. 3. We have obtained
this packing several times with s11 = 3.87708359 . . ., a result which is slightly better.

Their reference 3 is the very familiar E. Friedman, Packing unit squares in squares: a survey and new results, Electron. J. Combin. 7 (2000), #DS7.

The [online version of this paper](https://erich-friedman.github.io/papers/squares/squares.html)  does however list this as s(11)<3.8771 , different in the last digit from what Gensane & Ryckelynck quote.

Is this just a precision problem in the value originally published, or did Gensane & Ryckelynck find some distinct and subtly improved packing?

**Comment by erich-friedman** [comment]
it was a precision problem.  G&R found the same packing as trump.

erich

**Comment by hohMiyazawa** [comment]
Thank you
